### ISSUE TITLE
add JetStream Support

### ISSUE THREAD

**Issue by byu** [nats-io/nats.ex#114]
Nats 2.2+ has introduced the JetStream feature.
It would be nice to have this feature supported in this elixir client lib.

**Comment by mmmries** [comment]
I started work a little while ago on jetstream support as a separate package https://github.com/mmmries/jetstream

I'm not sure yet whether that code will get merged back into this project at some point, but I'm staring the effort there so we can explore what API we want to provide to users.

**Comment by mmmries** [comment]
Hi @kromnomo I am still actively maintaining this repository (keeping dependencies up to date, responding to issues, etc), but I haven't been actively working on support for the newest nats features such as Jetstream and Key-Value storage.

I would be happy to help answer questions or share the knowledge I have about Jetstream and this client if anyone else is interested in tackling that. But, for the moment I don't have the time to tackle this myself.

**Comment by kromnomo** [comment]
Thanks for your feedback. My knowledge of NATS is limited to its use, but I would be happy to help to the extent I can. 

If you could give me some insight about the open issues and the architecture approach of the client, that would be very helpful. For example, why is the JetStream client a separate project instead of a part of gnat?

**Comment by mmmries** [comment]
Hey @kromnomo there was no technical reasons for building jetstream as a separate repo, I was just wanting to keep my options very open while I was experimenting with different designs. Treating it as a separate repo meant I didn't have to manage branches or anything like that. But, I think the jetstream additions could be made to this library pretty easily.

In terms of the overall architecture, this client embraces a model where a single connection is encapsulated in a process. This makes the error handling very simple because you always have a fresh state when you establish a connection. For supervised connections we use a separate `ConnectionSupervisor` which starts up a connection with a name and then monitors it and will attempt a restart with a small backoff. This means the rest of the system can just try to use the configured name, but with the caveat that if the connection is down those function calls will fail.

I never got too deep into jetstream so I don't have a lot of suggestions about how to model a jetstream client, but I would probably start off by mirroring this same design aesthetic where you have some process that uses a `Gnat` connection to send/receive messages with the jetstream API and it could monitor that Gnat connection so that if the `Gnat` connection goes down, you can wait for it to come back up and then re-establish any subscriptions/etc.

**Comment by mmmries** [comment]
It may also be helpful to see how I had started to build out support for Nats Streaming in https://github.com/mmmries/nats.ex_streaming. But I think the more native approach of Jetstream will mean less complexity, so I'm hoping you would need less state-machine type logic

**Comment by autodidaddict** [comment]
What's the status of the JetStream exploration? Just today I was looking to take advantage of some of the object store stuff (that the Go client supports) that relies on JetStream. I might be writing some object store client code in the near future and I'd love to have a good place to put it.

Are you still working in this repo https://github.com/mmmries/jetstream ?

**Comment by mmmries** [comment]
@autodidaddict I was actually contacted by a company recently who is going to be sponsoring a few engineers to work on jetstream support ❤️💙💚💛. I am planning to work in the mmmries/jetstream repo you mentioned for now and once we have something working we'll decide whether we should pull it back into this library. I'm hoping to keep the support native in this library unless it has some significant external dependencies

**Comment by mmmries** [comment]
Support is coming along nicely in the https://github.com/mmmries/jetstream repo, I'm going to go ahead and close this ticket out for now. We may at some point pull this support back into this library, but for the foreseeable future we will develop jetstream support in a separately library so we can release often
