### ISSUE TITLE
Expect an erlang client

### ISSUE THREAD

**Issue by wwhai** [nats-io/nats.ex#118]
Expect an erlang client support.

**Comment by mmmries** [comment]
Thanks for raising this issue @wwhai. I don't have much experience working with erlang interfaces other than OTP standard libraries. Do you have any suggestions of how the interface should work?

Do you maybe know of other elixir projects that have added friendly erlang interfaces that I can go learn from?

**Comment by wwhai** [comment]
> Thanks for raising this issue @wwhai. I don't have much experience working with erlang interfaces other than OTP standard libraries. Do you have any suggestions of how the interface should work?
> 
> Do you maybe know of other elixir projects that have added friendly erlang interfaces that I can go learn from?
---
Yes, I known Elixir libiary can be used for erlang project, But we will do other mass work, such transform Elixir module to OTP module, or add Elixir stdlib to erlang path, etc.
I think should add directly support for erlang may be useful for erlang/otp developers?

**Comment by mmmries** [comment]
Thanks for sharing your perspective. I think making a library that integrates more easily to Erlang projects sounds really useful, but as I start thinking through what would be required, I think it may be outside the scope of this project.

In order to make sure that the elixir stdlib isn't a requirement I think we would need to really translate this whole library into an erlang project and then have this library wrap around the erlang one? I love supporting this project, but I don't have the time necessary to tackle that endeavor.

If I can help to provide support for someone else to tackle this endeavour I would love to help out, but I don't think this is within the time constraints that I have as of now.

**Comment by wwhai** [comment]
> Thanks for sharing your perspective. I think making a library that integrates more easily to Erlang projects sounds really useful, but as I start thinking through what would be required, I think it may be outside the scope of this project.
> 
> In order to make sure that the elixir stdlib isn't a requirement I think we would need to really translate this whole library into an erlang project and then have this library wrap around the erlang one? I love supporting this project, but I don't have the time necessary to tackle that endeavor.
> 
> If I can help to provide support for someone else to tackle this endeavour I would love to help out, but I don't think this is within the time constraints that I have as of now.

---
Wrap to an erlang project is a good idea.
